name: Build and Upload Docker Imageto ECR on prometheon-workload-jouleverne-dev

on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches:
      - main
  release:
    types: [created]

permissions:
  contents: read
  id-token: write

jobs:
  build-and-upload:
    runs-on: ubuntu-latest
    environment: prometheon-access

    strategy:
      matrix:
        - name: dev
          role: SFOE_JOULEVERNE_DEV_ROLE
        - name: prod
          role: SFOE_JOULEVERNE_PROD_ROLE

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ matrix.role }}
          aws-region: eu-central-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build, tag, and push Docker image to Amazon ECR (PR)
        if: github.event_name == 'pull_request' && matrix.env.name == 'dev'
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: jouleverne
          IMAGE_TAG: pr-${{ github.event.pull_request.number }}
        run: |
          docker build -t $ECR_REPOSITORY:$IMAGE_TAG .
          docker tag $ECR_REPOSITORY:$IMAGE_TAG $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

      - name: Build, tag, and push Docker image to Amazon ECR (main)
        if: github.event_name == 'push' && github.ref == 'refs/heads/main' && matrix.env.name == 'dev'
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: jouleverne
          IMAGE_TAG: latest
        run: |
          docker build -t $ECR_REPOSITORY:$IMAGE_TAG .
          docker tag $ECR_REPOSITORY:$IMAGE_TAG $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

      - name: Build, tag, and push Docker image to Amazon ECR (release)
        if: github.event_name == 'release'
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: jouleverne
          IMAGE_TAG: ${{ github.event.release.tag_name }}
        run: |
          docker build -t $ECR_REPOSITORY:$IMAGE_TAG .
          docker tag $ECR_REPOSITORY:$IMAGE_TAG $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG